server {
  listen 80;

  location / {
    proxy_pass http://app:3000; # 全てのリクエストをnode.js(app:3000)に転送する
  }

  location /css/ {
    root /usr/share/nginx/html; # cssやjsへのリクエストはnode.jsに転送せずにnginxが直接返却する(htmlのヘッダーに記載の部分)
  }

  location /javascript/ {
    root /usr/share/nginx/html;
  }
}
